services:
  soraai:
    image: rgpartners/soraai:latest
    ports:
      - '3000:3000'
    volumes:
      - uploads:/home/soraai/uploads
    restart: unless-stopped

volumes:
  uploads:
    name: 'soraai-uploads'
